server:
  port: 8002
spring:
  application:
    name: TTG-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ttg_product
    username: root
    password: admin
mybatis-plus:
  mapper-locations: classpath:cn/itsource/ttg/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.ttg.domain,cn.itsource.ttg.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true